version: '3.9'
services:
  db:
    image: postgres
    container_name: notes-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./packages/backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - shared-network
  backend:
    build: ./packages/backend
    container_name: notes-backend
    restart: always
    depends_on:
      - db
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PG_USER: ${PG_USER}
      PG_HOST: ${PG_HOST}
      PG_DATABASE: ${PG_DATABASE}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
      DATABASE_URL: postgres://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}
    ports:
      - "5000:5000"
    networks:
      - shared-network
  frontend:
    build: ./packages/frontend
    container_name: notes-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      - shared-network
volumes:
  pgdata:
networks:
  shared-network:
    external: true