services:
  db:
    image: postgres
    container_name: notes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Simon29maarawi
      POSTGRES_DB: notes_app_new
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - shared-network

  backend:
    build: .
    container_name: notes-backend
    restart: always
    depends_on:
      - db
    environment:
      JWT_SECRET: d0e4e7a6af74ffe07dfd86ff71af7204ee7730377f5fa4c8a6cdacb7b20f40044faa5fe69bd3653f996ab487351d7e6c07bd13a268288f9ced238a944966b203
      PG_USER: postgres
      PG_HOST: db
      PG_DATABASE: notes_app_new
      PG_PASSWORD: Simon29maarawi
      PG_PORT: 5432
    ports:
      - "5000:5000"
    networks:
      - shared-network

volumes:
  pgdata:

networks:
  shared-network:
    external: true
